/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * Carmentis indexer API
 * Documentation for the Carmentis indexer API.
 * OpenAPI spec version: 1.0
 */
import type { MicroblockProofVirtualBlockchainDto } from './microblockProofVirtualBlockchainDto.ts';
import type { ProofBlockDto } from './proofBlockDto.ts';

export interface AccountProofResponseDto {
  block: ProofBlockDto;
  account: MicroblockProofVirtualBlockchainDto;
}
