/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * Carmentis indexer API
 * Documentation for the Carmentis indexer API.
 * OpenAPI spec version: 1.0
 */
import type { AppControllerGetMicroblockStatsVbType } from './appControllerGetMicroblockStatsVbType.ts';

export type AppControllerGetMicroblockStatsParams = {
/**
 * Limits the stats to a specific virtual blockchain type.
 */
vb_type?: AppControllerGetMicroblockStatsVbType;
/**
 * Limits the stats to either genesis or non-genesis microblocks.
 */
is_genesis?: boolean;
/**
 * Minimum timestamp in milliseconds (inclusive). Resolution is 1 hour.
 */
timestamp_gte?: number;
/**
 * Maximum timestamp in milliseconds (inclusive). Resolution is 1 hour.
 */
timestamp_lte?: number;
};
