/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * Carmentis indexer API
 * Documentation for the Carmentis indexer API.
 * OpenAPI spec version: 1.0
 */
import type { MicroblockProofMicroblockDto } from './microblockProofMicroblockDto.ts';
import type { MicroblockProofVirtualBlockchainDto } from './microblockProofVirtualBlockchainDto.ts';
import type { ProofBlockDto } from './proofBlockDto.ts';

export interface MicroblockProofResponseDto {
  block: ProofBlockDto;
  microblock: MicroblockProofMicroblockDto;
  virtualBlockchain: MicroblockProofVirtualBlockchainDto;
}
