/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * Carmentis indexer API
 * Documentation for the Carmentis indexer API.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  AccountHistoryListResponseDto,
  AccountListResponseDto,
  AccountProofResponseDto,
  AppControllerGetAccountHistoryParams,
  AppControllerGetAccountProofParams,
  AppControllerGetAccountsParams,
  AppControllerGetApplicationsParams,
  AppControllerGetBlocksParams,
  AppControllerGetGasPriceParams,
  AppControllerGetMicroblockProofParams,
  AppControllerGetMicroblockStatsParams,
  AppControllerGetMicroblocksParams,
  AppControllerGetNodeStatusParams,
  AppControllerGetOrganizationsParams,
  AppControllerGetValidatorNodesParams,
  AppControllerGetVirtualBlockchainsParams,
  AppControllerGetVotingPowersParams,
  AppControllerSearchParams,
  ApplicationListResponseDto,
  BlockListResponseDto,
  ChainResponseDto,
  GasPriceResponseDto,
  MicroblockListResponseDto,
  MicroblockProofResponseDto,
  MicroblockStatsResponseDto,
  NodeStatusResponseDto,
  OrganizationListResponseDto,
  SearchListResponseDto,
  ValidatorNodeListResponseDto,
  VirtualBlockchainListResponseDto,
  VotingPowerListResponseDto
} from './model';

export type appControllerGetRootResponse200 = {
  data: void
  status: 200
}

export type appControllerGetRootResponseSuccess = (appControllerGetRootResponse200) & {
  headers: Headers;
};
;

export type appControllerGetRootResponse = (appControllerGetRootResponseSuccess)

export const getAppControllerGetRootUrl = () => {




  return `/api/v1`
}

export const appControllerGetRoot = async ( options?: RequestInit): Promise<appControllerGetRootResponse> => {

  const res = await fetch(getAppControllerGetRootUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appControllerGetRootResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as appControllerGetRootResponse
}





export const getAppControllerGetRootQueryKey = () => {
    return [
    'api','v1'
    ] as const;
    }


export const getAppControllerGetRootQueryOptions = <TData = Awaited<ReturnType<typeof appControllerGetRoot>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetRoot>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getAppControllerGetRootQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerGetRoot>>> = ({ signal }) => appControllerGetRoot({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appControllerGetRoot>>, TError, TData>
}

export type AppControllerGetRootQueryResult = NonNullable<Awaited<ReturnType<typeof appControllerGetRoot>>>
export type AppControllerGetRootQueryError = unknown



export function useAppControllerGetRoot<TData = Awaited<ReturnType<typeof appControllerGetRoot>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetRoot>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppControllerGetRootQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type appControllerGetChainResponse200 = {
  data: ChainResponseDto
  status: 200
}

export type appControllerGetChainResponseSuccess = (appControllerGetChainResponse200) & {
  headers: Headers;
};
;

export type appControllerGetChainResponse = (appControllerGetChainResponseSuccess)

export const getAppControllerGetChainUrl = () => {




  return `/api/v1/chain`
}

export const appControllerGetChain = async ( options?: RequestInit): Promise<appControllerGetChainResponse> => {

  const res = await fetch(getAppControllerGetChainUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appControllerGetChainResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appControllerGetChainResponse
}





export const getAppControllerGetChainQueryKey = () => {
    return [
    'api','v1','chain'
    ] as const;
    }


export const getAppControllerGetChainQueryOptions = <TData = Awaited<ReturnType<typeof appControllerGetChain>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetChain>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getAppControllerGetChainQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerGetChain>>> = ({ signal }) => appControllerGetChain({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appControllerGetChain>>, TError, TData>
}

export type AppControllerGetChainQueryResult = NonNullable<Awaited<ReturnType<typeof appControllerGetChain>>>
export type AppControllerGetChainQueryError = unknown



export function useAppControllerGetChain<TData = Awaited<ReturnType<typeof appControllerGetChain>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetChain>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppControllerGetChainQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type appControllerGetGasPriceResponse200 = {
  data: GasPriceResponseDto
  status: 200
}

export type appControllerGetGasPriceResponseSuccess = (appControllerGetGasPriceResponse200) & {
  headers: Headers;
};
;

export type appControllerGetGasPriceResponse = (appControllerGetGasPriceResponseSuccess)

export const getAppControllerGetGasPriceUrl = (params?: AppControllerGetGasPriceParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/gas-price?${stringifiedParams}` : `/api/v1/gas-price`
}

export const appControllerGetGasPrice = async (params?: AppControllerGetGasPriceParams, options?: RequestInit): Promise<appControllerGetGasPriceResponse> => {

  const res = await fetch(getAppControllerGetGasPriceUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appControllerGetGasPriceResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appControllerGetGasPriceResponse
}





export const getAppControllerGetGasPriceQueryKey = (params?: MaybeRef<AppControllerGetGasPriceParams>,) => {
    return [
    'api','v1','gas-price', ...(params ? [params] : [])
    ] as const;
    }


export const getAppControllerGetGasPriceQueryOptions = <TData = Awaited<ReturnType<typeof appControllerGetGasPrice>>, TError = unknown>(params?: MaybeRef<AppControllerGetGasPriceParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetGasPrice>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getAppControllerGetGasPriceQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerGetGasPrice>>> = ({ signal }) => appControllerGetGasPrice(unref(params), { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appControllerGetGasPrice>>, TError, TData>
}

export type AppControllerGetGasPriceQueryResult = NonNullable<Awaited<ReturnType<typeof appControllerGetGasPrice>>>
export type AppControllerGetGasPriceQueryError = unknown



export function useAppControllerGetGasPrice<TData = Awaited<ReturnType<typeof appControllerGetGasPrice>>, TError = unknown>(
 params?: MaybeRef<AppControllerGetGasPriceParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetGasPrice>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppControllerGetGasPriceQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type appControllerSearchResponse200 = {
  data: SearchListResponseDto
  status: 200
}

export type appControllerSearchResponseSuccess = (appControllerSearchResponse200) & {
  headers: Headers;
};
;

export type appControllerSearchResponse = (appControllerSearchResponseSuccess)

export const getAppControllerSearchUrl = (params: AppControllerSearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/search?${stringifiedParams}` : `/api/v1/search`
}

export const appControllerSearch = async (params: AppControllerSearchParams, options?: RequestInit): Promise<appControllerSearchResponse> => {

  const res = await fetch(getAppControllerSearchUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appControllerSearchResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appControllerSearchResponse
}





export const getAppControllerSearchQueryKey = (params?: MaybeRef<AppControllerSearchParams>,) => {
    return [
    'api','v1','search', ...(params ? [params] : [])
    ] as const;
    }


export const getAppControllerSearchQueryOptions = <TData = Awaited<ReturnType<typeof appControllerSearch>>, TError = unknown>(params: MaybeRef<AppControllerSearchParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerSearch>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getAppControllerSearchQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerSearch>>> = ({ signal }) => appControllerSearch(unref(params), { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appControllerSearch>>, TError, TData>
}

export type AppControllerSearchQueryResult = NonNullable<Awaited<ReturnType<typeof appControllerSearch>>>
export type AppControllerSearchQueryError = unknown



export function useAppControllerSearch<TData = Awaited<ReturnType<typeof appControllerSearch>>, TError = unknown>(
 params: MaybeRef<AppControllerSearchParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerSearch>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppControllerSearchQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type appControllerGetBlocksResponse200 = {
  data: BlockListResponseDto
  status: 200
}

export type appControllerGetBlocksResponseSuccess = (appControllerGetBlocksResponse200) & {
  headers: Headers;
};
;

export type appControllerGetBlocksResponse = (appControllerGetBlocksResponseSuccess)

export const getAppControllerGetBlocksUrl = (params?: AppControllerGetBlocksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/blocks?${stringifiedParams}` : `/api/v1/blocks`
}

export const appControllerGetBlocks = async (params?: AppControllerGetBlocksParams, options?: RequestInit): Promise<appControllerGetBlocksResponse> => {

  const res = await fetch(getAppControllerGetBlocksUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appControllerGetBlocksResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appControllerGetBlocksResponse
}





export const getAppControllerGetBlocksQueryKey = (params?: MaybeRef<AppControllerGetBlocksParams>,) => {
    return [
    'api','v1','blocks', ...(params ? [params] : [])
    ] as const;
    }


export const getAppControllerGetBlocksQueryOptions = <TData = Awaited<ReturnType<typeof appControllerGetBlocks>>, TError = unknown>(params?: MaybeRef<AppControllerGetBlocksParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetBlocks>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getAppControllerGetBlocksQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerGetBlocks>>> = ({ signal }) => appControllerGetBlocks(unref(params), { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appControllerGetBlocks>>, TError, TData>
}

export type AppControllerGetBlocksQueryResult = NonNullable<Awaited<ReturnType<typeof appControllerGetBlocks>>>
export type AppControllerGetBlocksQueryError = unknown



export function useAppControllerGetBlocks<TData = Awaited<ReturnType<typeof appControllerGetBlocks>>, TError = unknown>(
 params?: MaybeRef<AppControllerGetBlocksParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetBlocks>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppControllerGetBlocksQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type appControllerGetMicroblocksResponse200 = {
  data: MicroblockListResponseDto
  status: 200
}

export type appControllerGetMicroblocksResponseSuccess = (appControllerGetMicroblocksResponse200) & {
  headers: Headers;
};
;

export type appControllerGetMicroblocksResponse = (appControllerGetMicroblocksResponseSuccess)

export const getAppControllerGetMicroblocksUrl = (params?: AppControllerGetMicroblocksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/microblocks?${stringifiedParams}` : `/api/v1/microblocks`
}

export const appControllerGetMicroblocks = async (params?: AppControllerGetMicroblocksParams, options?: RequestInit): Promise<appControllerGetMicroblocksResponse> => {

  const res = await fetch(getAppControllerGetMicroblocksUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appControllerGetMicroblocksResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appControllerGetMicroblocksResponse
}





export const getAppControllerGetMicroblocksQueryKey = (params?: MaybeRef<AppControllerGetMicroblocksParams>,) => {
    return [
    'api','v1','microblocks', ...(params ? [params] : [])
    ] as const;
    }


export const getAppControllerGetMicroblocksQueryOptions = <TData = Awaited<ReturnType<typeof appControllerGetMicroblocks>>, TError = unknown>(params?: MaybeRef<AppControllerGetMicroblocksParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetMicroblocks>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getAppControllerGetMicroblocksQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerGetMicroblocks>>> = ({ signal }) => appControllerGetMicroblocks(unref(params), { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appControllerGetMicroblocks>>, TError, TData>
}

export type AppControllerGetMicroblocksQueryResult = NonNullable<Awaited<ReturnType<typeof appControllerGetMicroblocks>>>
export type AppControllerGetMicroblocksQueryError = unknown



export function useAppControllerGetMicroblocks<TData = Awaited<ReturnType<typeof appControllerGetMicroblocks>>, TError = unknown>(
 params?: MaybeRef<AppControllerGetMicroblocksParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetMicroblocks>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppControllerGetMicroblocksQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type appControllerGetMicroblockProofResponse200 = {
  data: MicroblockProofResponseDto
  status: 200
}

export type appControllerGetMicroblockProofResponseSuccess = (appControllerGetMicroblockProofResponse200) & {
  headers: Headers;
};
;

export type appControllerGetMicroblockProofResponse = (appControllerGetMicroblockProofResponseSuccess)

export const getAppControllerGetMicroblockProofUrl = (params: AppControllerGetMicroblockProofParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/microblock-proof?${stringifiedParams}` : `/api/v1/microblock-proof`
}

export const appControllerGetMicroblockProof = async (params: AppControllerGetMicroblockProofParams, options?: RequestInit): Promise<appControllerGetMicroblockProofResponse> => {

  const res = await fetch(getAppControllerGetMicroblockProofUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appControllerGetMicroblockProofResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appControllerGetMicroblockProofResponse
}





export const getAppControllerGetMicroblockProofQueryKey = (params?: MaybeRef<AppControllerGetMicroblockProofParams>,) => {
    return [
    'api','v1','microblock-proof', ...(params ? [params] : [])
    ] as const;
    }


export const getAppControllerGetMicroblockProofQueryOptions = <TData = Awaited<ReturnType<typeof appControllerGetMicroblockProof>>, TError = unknown>(params: MaybeRef<AppControllerGetMicroblockProofParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetMicroblockProof>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getAppControllerGetMicroblockProofQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerGetMicroblockProof>>> = ({ signal }) => appControllerGetMicroblockProof(unref(params), { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appControllerGetMicroblockProof>>, TError, TData>
}

export type AppControllerGetMicroblockProofQueryResult = NonNullable<Awaited<ReturnType<typeof appControllerGetMicroblockProof>>>
export type AppControllerGetMicroblockProofQueryError = unknown



export function useAppControllerGetMicroblockProof<TData = Awaited<ReturnType<typeof appControllerGetMicroblockProof>>, TError = unknown>(
 params: MaybeRef<AppControllerGetMicroblockProofParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetMicroblockProof>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppControllerGetMicroblockProofQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type appControllerGetMicroblockStatsResponse200 = {
  data: MicroblockStatsResponseDto
  status: 200
}

export type appControllerGetMicroblockStatsResponseSuccess = (appControllerGetMicroblockStatsResponse200) & {
  headers: Headers;
};
;

export type appControllerGetMicroblockStatsResponse = (appControllerGetMicroblockStatsResponseSuccess)

export const getAppControllerGetMicroblockStatsUrl = (params?: AppControllerGetMicroblockStatsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/microblock-stats?${stringifiedParams}` : `/api/v1/microblock-stats`
}

export const appControllerGetMicroblockStats = async (params?: AppControllerGetMicroblockStatsParams, options?: RequestInit): Promise<appControllerGetMicroblockStatsResponse> => {

  const res = await fetch(getAppControllerGetMicroblockStatsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appControllerGetMicroblockStatsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appControllerGetMicroblockStatsResponse
}





export const getAppControllerGetMicroblockStatsQueryKey = (params?: MaybeRef<AppControllerGetMicroblockStatsParams>,) => {
    return [
    'api','v1','microblock-stats', ...(params ? [params] : [])
    ] as const;
    }


export const getAppControllerGetMicroblockStatsQueryOptions = <TData = Awaited<ReturnType<typeof appControllerGetMicroblockStats>>, TError = unknown>(params?: MaybeRef<AppControllerGetMicroblockStatsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetMicroblockStats>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getAppControllerGetMicroblockStatsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerGetMicroblockStats>>> = ({ signal }) => appControllerGetMicroblockStats(unref(params), { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appControllerGetMicroblockStats>>, TError, TData>
}

export type AppControllerGetMicroblockStatsQueryResult = NonNullable<Awaited<ReturnType<typeof appControllerGetMicroblockStats>>>
export type AppControllerGetMicroblockStatsQueryError = unknown



export function useAppControllerGetMicroblockStats<TData = Awaited<ReturnType<typeof appControllerGetMicroblockStats>>, TError = unknown>(
 params?: MaybeRef<AppControllerGetMicroblockStatsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetMicroblockStats>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppControllerGetMicroblockStatsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type appControllerGetAccountsResponse200 = {
  data: AccountListResponseDto
  status: 200
}

export type appControllerGetAccountsResponseSuccess = (appControllerGetAccountsResponse200) & {
  headers: Headers;
};
;

export type appControllerGetAccountsResponse = (appControllerGetAccountsResponseSuccess)

export const getAppControllerGetAccountsUrl = (params?: AppControllerGetAccountsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/accounts?${stringifiedParams}` : `/api/v1/accounts`
}

export const appControllerGetAccounts = async (params?: AppControllerGetAccountsParams, options?: RequestInit): Promise<appControllerGetAccountsResponse> => {

  const res = await fetch(getAppControllerGetAccountsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appControllerGetAccountsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appControllerGetAccountsResponse
}





export const getAppControllerGetAccountsQueryKey = (params?: MaybeRef<AppControllerGetAccountsParams>,) => {
    return [
    'api','v1','accounts', ...(params ? [params] : [])
    ] as const;
    }


export const getAppControllerGetAccountsQueryOptions = <TData = Awaited<ReturnType<typeof appControllerGetAccounts>>, TError = unknown>(params?: MaybeRef<AppControllerGetAccountsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetAccounts>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getAppControllerGetAccountsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerGetAccounts>>> = ({ signal }) => appControllerGetAccounts(unref(params), { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appControllerGetAccounts>>, TError, TData>
}

export type AppControllerGetAccountsQueryResult = NonNullable<Awaited<ReturnType<typeof appControllerGetAccounts>>>
export type AppControllerGetAccountsQueryError = unknown



export function useAppControllerGetAccounts<TData = Awaited<ReturnType<typeof appControllerGetAccounts>>, TError = unknown>(
 params?: MaybeRef<AppControllerGetAccountsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetAccounts>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppControllerGetAccountsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type appControllerGetAccountHistoryResponse200 = {
  data: AccountHistoryListResponseDto
  status: 200
}

export type appControllerGetAccountHistoryResponseSuccess = (appControllerGetAccountHistoryResponse200) & {
  headers: Headers;
};
;

export type appControllerGetAccountHistoryResponse = (appControllerGetAccountHistoryResponseSuccess)

export const getAppControllerGetAccountHistoryUrl = (params?: AppControllerGetAccountHistoryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/account-history?${stringifiedParams}` : `/api/v1/account-history`
}

export const appControllerGetAccountHistory = async (params?: AppControllerGetAccountHistoryParams, options?: RequestInit): Promise<appControllerGetAccountHistoryResponse> => {

  const res = await fetch(getAppControllerGetAccountHistoryUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appControllerGetAccountHistoryResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appControllerGetAccountHistoryResponse
}





export const getAppControllerGetAccountHistoryQueryKey = (params?: MaybeRef<AppControllerGetAccountHistoryParams>,) => {
    return [
    'api','v1','account-history', ...(params ? [params] : [])
    ] as const;
    }


export const getAppControllerGetAccountHistoryQueryOptions = <TData = Awaited<ReturnType<typeof appControllerGetAccountHistory>>, TError = unknown>(params?: MaybeRef<AppControllerGetAccountHistoryParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetAccountHistory>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getAppControllerGetAccountHistoryQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerGetAccountHistory>>> = ({ signal }) => appControllerGetAccountHistory(unref(params), { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appControllerGetAccountHistory>>, TError, TData>
}

export type AppControllerGetAccountHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof appControllerGetAccountHistory>>>
export type AppControllerGetAccountHistoryQueryError = unknown



export function useAppControllerGetAccountHistory<TData = Awaited<ReturnType<typeof appControllerGetAccountHistory>>, TError = unknown>(
 params?: MaybeRef<AppControllerGetAccountHistoryParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetAccountHistory>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppControllerGetAccountHistoryQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type appControllerGetAccountProofResponse200 = {
  data: AccountProofResponseDto
  status: 200
}

export type appControllerGetAccountProofResponseSuccess = (appControllerGetAccountProofResponse200) & {
  headers: Headers;
};
;

export type appControllerGetAccountProofResponse = (appControllerGetAccountProofResponseSuccess)

export const getAppControllerGetAccountProofUrl = (params: AppControllerGetAccountProofParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/account-proof?${stringifiedParams}` : `/api/v1/account-proof`
}

export const appControllerGetAccountProof = async (params: AppControllerGetAccountProofParams, options?: RequestInit): Promise<appControllerGetAccountProofResponse> => {

  const res = await fetch(getAppControllerGetAccountProofUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appControllerGetAccountProofResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appControllerGetAccountProofResponse
}





export const getAppControllerGetAccountProofQueryKey = (params?: MaybeRef<AppControllerGetAccountProofParams>,) => {
    return [
    'api','v1','account-proof', ...(params ? [params] : [])
    ] as const;
    }


export const getAppControllerGetAccountProofQueryOptions = <TData = Awaited<ReturnType<typeof appControllerGetAccountProof>>, TError = unknown>(params: MaybeRef<AppControllerGetAccountProofParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetAccountProof>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getAppControllerGetAccountProofQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerGetAccountProof>>> = ({ signal }) => appControllerGetAccountProof(unref(params), { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appControllerGetAccountProof>>, TError, TData>
}

export type AppControllerGetAccountProofQueryResult = NonNullable<Awaited<ReturnType<typeof appControllerGetAccountProof>>>
export type AppControllerGetAccountProofQueryError = unknown



export function useAppControllerGetAccountProof<TData = Awaited<ReturnType<typeof appControllerGetAccountProof>>, TError = unknown>(
 params: MaybeRef<AppControllerGetAccountProofParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetAccountProof>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppControllerGetAccountProofQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type appControllerGetOrganizationsResponse200 = {
  data: OrganizationListResponseDto
  status: 200
}

export type appControllerGetOrganizationsResponseSuccess = (appControllerGetOrganizationsResponse200) & {
  headers: Headers;
};
;

export type appControllerGetOrganizationsResponse = (appControllerGetOrganizationsResponseSuccess)

export const getAppControllerGetOrganizationsUrl = (params?: AppControllerGetOrganizationsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/organizations?${stringifiedParams}` : `/api/v1/organizations`
}

export const appControllerGetOrganizations = async (params?: AppControllerGetOrganizationsParams, options?: RequestInit): Promise<appControllerGetOrganizationsResponse> => {

  const res = await fetch(getAppControllerGetOrganizationsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appControllerGetOrganizationsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appControllerGetOrganizationsResponse
}





export const getAppControllerGetOrganizationsQueryKey = (params?: MaybeRef<AppControllerGetOrganizationsParams>,) => {
    return [
    'api','v1','organizations', ...(params ? [params] : [])
    ] as const;
    }


export const getAppControllerGetOrganizationsQueryOptions = <TData = Awaited<ReturnType<typeof appControllerGetOrganizations>>, TError = unknown>(params?: MaybeRef<AppControllerGetOrganizationsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetOrganizations>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getAppControllerGetOrganizationsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerGetOrganizations>>> = ({ signal }) => appControllerGetOrganizations(unref(params), { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appControllerGetOrganizations>>, TError, TData>
}

export type AppControllerGetOrganizationsQueryResult = NonNullable<Awaited<ReturnType<typeof appControllerGetOrganizations>>>
export type AppControllerGetOrganizationsQueryError = unknown



export function useAppControllerGetOrganizations<TData = Awaited<ReturnType<typeof appControllerGetOrganizations>>, TError = unknown>(
 params?: MaybeRef<AppControllerGetOrganizationsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetOrganizations>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppControllerGetOrganizationsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type appControllerGetApplicationsResponse200 = {
  data: ApplicationListResponseDto
  status: 200
}

export type appControllerGetApplicationsResponseSuccess = (appControllerGetApplicationsResponse200) & {
  headers: Headers;
};
;

export type appControllerGetApplicationsResponse = (appControllerGetApplicationsResponseSuccess)

export const getAppControllerGetApplicationsUrl = (params?: AppControllerGetApplicationsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/applications?${stringifiedParams}` : `/api/v1/applications`
}

export const appControllerGetApplications = async (params?: AppControllerGetApplicationsParams, options?: RequestInit): Promise<appControllerGetApplicationsResponse> => {

  const res = await fetch(getAppControllerGetApplicationsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appControllerGetApplicationsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appControllerGetApplicationsResponse
}





export const getAppControllerGetApplicationsQueryKey = (params?: MaybeRef<AppControllerGetApplicationsParams>,) => {
    return [
    'api','v1','applications', ...(params ? [params] : [])
    ] as const;
    }


export const getAppControllerGetApplicationsQueryOptions = <TData = Awaited<ReturnType<typeof appControllerGetApplications>>, TError = unknown>(params?: MaybeRef<AppControllerGetApplicationsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetApplications>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getAppControllerGetApplicationsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerGetApplications>>> = ({ signal }) => appControllerGetApplications(unref(params), { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appControllerGetApplications>>, TError, TData>
}

export type AppControllerGetApplicationsQueryResult = NonNullable<Awaited<ReturnType<typeof appControllerGetApplications>>>
export type AppControllerGetApplicationsQueryError = unknown



export function useAppControllerGetApplications<TData = Awaited<ReturnType<typeof appControllerGetApplications>>, TError = unknown>(
 params?: MaybeRef<AppControllerGetApplicationsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetApplications>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppControllerGetApplicationsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type appControllerGetValidatorNodesResponse200 = {
  data: ValidatorNodeListResponseDto
  status: 200
}

export type appControllerGetValidatorNodesResponseSuccess = (appControllerGetValidatorNodesResponse200) & {
  headers: Headers;
};
;

export type appControllerGetValidatorNodesResponse = (appControllerGetValidatorNodesResponseSuccess)

export const getAppControllerGetValidatorNodesUrl = (params?: AppControllerGetValidatorNodesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/validator-nodes?${stringifiedParams}` : `/api/v1/validator-nodes`
}

export const appControllerGetValidatorNodes = async (params?: AppControllerGetValidatorNodesParams, options?: RequestInit): Promise<appControllerGetValidatorNodesResponse> => {

  const res = await fetch(getAppControllerGetValidatorNodesUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appControllerGetValidatorNodesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appControllerGetValidatorNodesResponse
}





export const getAppControllerGetValidatorNodesQueryKey = (params?: MaybeRef<AppControllerGetValidatorNodesParams>,) => {
    return [
    'api','v1','validator-nodes', ...(params ? [params] : [])
    ] as const;
    }


export const getAppControllerGetValidatorNodesQueryOptions = <TData = Awaited<ReturnType<typeof appControllerGetValidatorNodes>>, TError = unknown>(params?: MaybeRef<AppControllerGetValidatorNodesParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetValidatorNodes>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getAppControllerGetValidatorNodesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerGetValidatorNodes>>> = ({ signal }) => appControllerGetValidatorNodes(unref(params), { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appControllerGetValidatorNodes>>, TError, TData>
}

export type AppControllerGetValidatorNodesQueryResult = NonNullable<Awaited<ReturnType<typeof appControllerGetValidatorNodes>>>
export type AppControllerGetValidatorNodesQueryError = unknown



export function useAppControllerGetValidatorNodes<TData = Awaited<ReturnType<typeof appControllerGetValidatorNodes>>, TError = unknown>(
 params?: MaybeRef<AppControllerGetValidatorNodesParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetValidatorNodes>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppControllerGetValidatorNodesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type appControllerGetNodeStatusResponse200 = {
  data: NodeStatusResponseDto
  status: 200
}

export type appControllerGetNodeStatusResponseSuccess = (appControllerGetNodeStatusResponse200) & {
  headers: Headers;
};
;

export type appControllerGetNodeStatusResponse = (appControllerGetNodeStatusResponseSuccess)

export const getAppControllerGetNodeStatusUrl = (params: AppControllerGetNodeStatusParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/node-status?${stringifiedParams}` : `/api/v1/node-status`
}

export const appControllerGetNodeStatus = async (params: AppControllerGetNodeStatusParams, options?: RequestInit): Promise<appControllerGetNodeStatusResponse> => {

  const res = await fetch(getAppControllerGetNodeStatusUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appControllerGetNodeStatusResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appControllerGetNodeStatusResponse
}





export const getAppControllerGetNodeStatusQueryKey = (params?: MaybeRef<AppControllerGetNodeStatusParams>,) => {
    return [
    'api','v1','node-status', ...(params ? [params] : [])
    ] as const;
    }


export const getAppControllerGetNodeStatusQueryOptions = <TData = Awaited<ReturnType<typeof appControllerGetNodeStatus>>, TError = unknown>(params: MaybeRef<AppControllerGetNodeStatusParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetNodeStatus>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getAppControllerGetNodeStatusQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerGetNodeStatus>>> = ({ signal }) => appControllerGetNodeStatus(unref(params), { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appControllerGetNodeStatus>>, TError, TData>
}

export type AppControllerGetNodeStatusQueryResult = NonNullable<Awaited<ReturnType<typeof appControllerGetNodeStatus>>>
export type AppControllerGetNodeStatusQueryError = unknown



export function useAppControllerGetNodeStatus<TData = Awaited<ReturnType<typeof appControllerGetNodeStatus>>, TError = unknown>(
 params: MaybeRef<AppControllerGetNodeStatusParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetNodeStatus>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppControllerGetNodeStatusQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type appControllerGetVirtualBlockchainsResponse200 = {
  data: VirtualBlockchainListResponseDto
  status: 200
}

export type appControllerGetVirtualBlockchainsResponseSuccess = (appControllerGetVirtualBlockchainsResponse200) & {
  headers: Headers;
};
;

export type appControllerGetVirtualBlockchainsResponse = (appControllerGetVirtualBlockchainsResponseSuccess)

export const getAppControllerGetVirtualBlockchainsUrl = (params?: AppControllerGetVirtualBlockchainsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/virtual-blockchains?${stringifiedParams}` : `/api/v1/virtual-blockchains`
}

export const appControllerGetVirtualBlockchains = async (params?: AppControllerGetVirtualBlockchainsParams, options?: RequestInit): Promise<appControllerGetVirtualBlockchainsResponse> => {

  const res = await fetch(getAppControllerGetVirtualBlockchainsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appControllerGetVirtualBlockchainsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appControllerGetVirtualBlockchainsResponse
}





export const getAppControllerGetVirtualBlockchainsQueryKey = (params?: MaybeRef<AppControllerGetVirtualBlockchainsParams>,) => {
    return [
    'api','v1','virtual-blockchains', ...(params ? [params] : [])
    ] as const;
    }


export const getAppControllerGetVirtualBlockchainsQueryOptions = <TData = Awaited<ReturnType<typeof appControllerGetVirtualBlockchains>>, TError = unknown>(params?: MaybeRef<AppControllerGetVirtualBlockchainsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetVirtualBlockchains>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getAppControllerGetVirtualBlockchainsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerGetVirtualBlockchains>>> = ({ signal }) => appControllerGetVirtualBlockchains(unref(params), { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appControllerGetVirtualBlockchains>>, TError, TData>
}

export type AppControllerGetVirtualBlockchainsQueryResult = NonNullable<Awaited<ReturnType<typeof appControllerGetVirtualBlockchains>>>
export type AppControllerGetVirtualBlockchainsQueryError = unknown



export function useAppControllerGetVirtualBlockchains<TData = Awaited<ReturnType<typeof appControllerGetVirtualBlockchains>>, TError = unknown>(
 params?: MaybeRef<AppControllerGetVirtualBlockchainsParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetVirtualBlockchains>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppControllerGetVirtualBlockchainsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}







export type appControllerGetVotingPowersResponse200 = {
  data: VotingPowerListResponseDto
  status: 200
}

export type appControllerGetVotingPowersResponseSuccess = (appControllerGetVotingPowersResponse200) & {
  headers: Headers;
};
;

export type appControllerGetVotingPowersResponse = (appControllerGetVotingPowersResponseSuccess)

export const getAppControllerGetVotingPowersUrl = (params?: AppControllerGetVotingPowersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/voting-powers?${stringifiedParams}` : `/api/v1/voting-powers`
}

export const appControllerGetVotingPowers = async (params?: AppControllerGetVotingPowersParams, options?: RequestInit): Promise<appControllerGetVotingPowersResponse> => {

  const res = await fetch(getAppControllerGetVotingPowersUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appControllerGetVotingPowersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appControllerGetVotingPowersResponse
}





export const getAppControllerGetVotingPowersQueryKey = (params?: MaybeRef<AppControllerGetVotingPowersParams>,) => {
    return [
    'api','v1','voting-powers', ...(params ? [params] : [])
    ] as const;
    }


export const getAppControllerGetVotingPowersQueryOptions = <TData = Awaited<ReturnType<typeof appControllerGetVotingPowers>>, TError = unknown>(params?: MaybeRef<AppControllerGetVotingPowersParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetVotingPowers>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  getAppControllerGetVotingPowersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerGetVotingPowers>>> = ({ signal }) => appControllerGetVotingPowers(unref(params), { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appControllerGetVotingPowers>>, TError, TData>
}

export type AppControllerGetVotingPowersQueryResult = NonNullable<Awaited<ReturnType<typeof appControllerGetVotingPowers>>>
export type AppControllerGetVotingPowersQueryError = unknown



export function useAppControllerGetVotingPowers<TData = Awaited<ReturnType<typeof appControllerGetVotingPowers>>, TError = unknown>(
 params?: MaybeRef<AppControllerGetVotingPowersParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetVotingPowers>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppControllerGetVotingPowersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}
